In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3,4])

In [3]:
 myarr

array([1, 2, 3, 4])

***1)Given space as bytes for numbers or any other***


In [4]:
myarr1 = np.array(myarr,np.int32)

In [5]:
myarr1


array([1, 2, 3, 4], dtype=int32)

***2)Accessing Elements in Array and printing***

In [6]:
print(myarr1[1])


2


***3)Updating specific index with new element***

In [7]:
myarr1[1] = 33

In [10]:
myarr1

array([ 1, 33,  3,  4], dtype=int32)

# Knowing about the size/dimensions of an array

In [8]:
myarr1.shape


(4,)

# Knowing about dtype tells the data type of elements stored in a NumPy array.

In [9]:
myarr1.dtype

dtype('int32')

# Array Creation Method 1: Conversion from other Python structures

In [13]:
listarr = np.array([[1,2,3],[5,4,5],[0,3,1]])

In [14]:
listarr.shape


(3, 3)

In [15]:
listarr.size

9

# Adding Zeros into Array using the Zeroes Function

In [16]:
zer = np.zeros((2,5))

In [18]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Adding Elements from 0 to n-1 using arange funtion

In [19]:
n = 22
rng = np.arange(n)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

# linspace() in NumPy is used to create numbers equally spaced between a start and end value.

In [21]:
lspace = np.linspace(0,10,6)

In [22]:
lspace

array([ 0.,  2.,  4.,  6.,  8., 10.])

# np.empty() creates an array with given shape without assigning initial values and adds random values.

em = np.empty((4,6))

In [26]:
em

array([[1.11565697e-311, 1.11565882e-311, 1.11565882e-311,
        1.11565865e-311, 1.11565865e-311, 1.11565865e-311],
       [1.11565865e-311, 1.11565865e-311, 1.11565865e-311,
        1.11565865e-311, 1.11565865e-311, 1.11565865e-311],
       [1.11565865e-311, 1.11565865e-311, 1.11565865e-311,
        1.11565865e-311, 1.11565865e-311, 1.11565865e-311],
       [1.11565865e-311, 1.11565865e-311, 1.11565865e-311,
        1.11565865e-311, 1.11565865e-311, 1.11565865e-311]])

# np.empty_like() creates a new array with same shape and datatype as another array, but with random/uninitialized values.

In [27]:
el = np.empty_like(lspace)

In [28]:
el

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Creating Identity Matrix

In [29]:
id = np.identity(3) # creates 3 X 3 identity matrix

In [30]:
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# reshape() is used to change the shape/dimensions of a NumPy array.

In [33]:
res = rng.reshape(2,11) # convert 22X1 matrix to 11X2

In [32]:
res

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

# ravel() converts a multi-dimensional array into a 1D flattened array.

In [34]:
arr = res.ravel()

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

# axis tells NumPy in which direction operation should happen.

***1) axis = 0  → column wise (top to bottom)***

In [36]:
axS = res.sum(axis=0)

In [37]:
axS

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

***2) axis = 1  → row wise (left to right)***

In [38]:
axS1 = res.sum(axis=1)

In [39]:
axS1

array([ 55, 176])

# Transpose Array

In [41]:
res.T

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 5, 16],
       [ 6, 17],
       [ 7, 18],
       [ 8, 19],
       [ 9, 20],
       [10, 21]])

# flat is used to iterate through all elements of a NumPy array as a 1D iterator.

In [42]:
for i in res.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


***1) Accessing Elements using flat***

In [43]:
print(res.flat[2])

2


# ndim means number of dimensions of a NumPy array.

In [44]:
res.ndim

2

# nbytes tells how many total bytes of memory a NumPy array uses.

In [45]:
res.nbytes

176

# argmax() returns the index position of the maximum value in a NumPy array and for min argmin().

In [47]:
print(res.argmax())

21


In [48]:
print(res.argmin())

0


# argsort() sorts the array and returns it in sorted index format

In [50]:
a = np.array([3,99,1,0,90])
a.argsort()

array([3, 2, 0, 4, 1])

# argmax() and argsort() in 2d array

***1)Argmax with axis = 0***


In [51]:
s = np.array([[1,2,3],[5,4,5],[0,3,1]])
s.argmax(axis=0)

array([1, 1, 1])

***2) Argmax with axis = 1***

In [52]:
s.argmax(axis=1)

array([2, 0, 1])

***3) Argsort() with axis = 0***

In [53]:
s.argsort(axis=0)

array([[2, 0, 2],
       [0, 2, 0],
       [1, 1, 1]])

***4)Argsort() with axis = 1***

In [54]:
s.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [0, 2, 1]])

# Matrix Operations in Numpy

***1) Addtion of Matrices***

In [55]:
s1 = np.array([[1,2,1],[4,0,6],[8,1,0]])
s + s1

array([[ 2,  4,  4],
       [ 9,  4, 11],
       [ 8,  4,  1]])

***2) Multiplication of matrices***

In [56]:
s * s1

array([[ 1,  4,  3],
       [20,  0, 30],
       [ 0,  3,  0]])

***2) Sqrt in numpy***

In [57]:
np.sqrt(s1)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

***3) Determinant of matrix***

In [72]:
print(np.linalg.det(s1))

93.99999999999991


***5) Inverse of matrix***

In [73]:
print(np.linalg.inv(s1))

[[-0.06382979  0.0106383   0.12765957]
 [ 0.5106383  -0.08510638 -0.0212766 ]
 [ 0.04255319  0.15957447 -0.08510638]]


# Sum of all Elements in n-dimensional array

In [59]:
print(s1.sum())


23


# Max funtion return alues but argmax() return maxindex same for min

In [60]:
print(s1.max())

8


# np.where() is used to find elements based on a condition.

In [62]:
arr1 = np.array([10, 20, 30, 40, 50])

print(np.where(arr1 > 25))

(array([2, 3, 4]),)


# funtion to count number of non-zero elements

In [64]:
print(np.count_nonzero(arr1))

5


# nonzero() is used to find the indexes of non-zero elements in a NumPy array.

In [65]:
print(np.nonzero(arr1))

(array([0, 1, 2, 3, 4]),)



# Statistical Operations

***1) Mean of all numbers in array***

In [67]:
print(np.mean(arr1))

30.0


***2) Median of all numbers in the array***

In [68]:
print(np.median(arr1))

30.0


# Vector Dot Product

In [74]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vdot(a,b))

32


# Eigen Values and Eigen Vectors

In [75]:
m = np.array([[1, 2],
              [2, 3]])
w,v = np.linalg.eig(m)
print(w,v)

[-0.23606798  4.23606798] [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
